<Project>

    <!-- Global build configuration -->
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>true</ImplicitUsings>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>

</Project>
